BASE_STATION_AMOUNT = 50
YEARS_PASSED        = 8
N_CU_PER_DPC        = 1

# COMMON CAPEX VALUES
OPTIC_1_KM_DIG          = 3000
OPTIC_1_KM_ROLL         = 1000
SITE_MAST_INSTALL       = 15000
COMISSION_WORK_PERCENT  = 0.2

# COMMON OPEX VALUES
WATT_HOUR_COST          = 0.000673
OPTIC_1_KM_MAINTENANCE  = 50
SITE_RENT_PER_YEAR      = 5000
WAGE_PER_MONTH          = 2700
OEM_PERCENT             = 0.1
HOURS_PER_YEAR          = 24*365
SOFTWARE_UPDATE_PERCENT = 0.3

# DRAN CAPEX VALUES
DRAN_RU_BUY_COST        = 9000
DRAN_DU_BUY_COST        = 3000
DRAN_CU_BUY_COST        = 6000
DRAN_CPRI_BUY_COST      = 2500
DRAN_COOLING_BUY_COST   = 3000
        
# DRAN OPEX VALUES
DRAN_RU_POWER_CONSUMPTION       = 500
DRAN_DU_CU_POWER_CONSUMPTION    = 400
DRAN_COOLING_POWER_CONSUMPTION  = 500
    

# ORAN CAPEX VALUES
ORAN_RU_BUY_COST 			= 6000
ORAN_VIRTUAL_DU_BUY_COST    = 3500   # Этот параметр означает не программу, а часть физического сервера
ORAN_VIRTUAL_CU_BUY_COST    = 5000
ORAN_ETHERNET_BUY_COST      = 150
ORAN_DPC_BUILD_PER_RACK     = 34852
ORAN_RU_SOFTWARE_BUY_COST   = 200
ORAN_DU_SOFTWARE_BUY_COST   = 400
ORAN_CU_SOFTWARE_BUY_COST   = 400
ORAN_DPC_COOLING            = 5000
N_PHY_SERVERS_PER_RACK      = 20
        
# ORAN OPEX VALUES
ORAN_RU_POWER_CONSUMPTION           = 500
ORAN_VIRTUAL_DU_POWER_CONSUMPTION   = 500   # Сервер содержащий 3 виртуальных DU потребляет 1500 Ватт*час
ORAN_VIRTUAL_CU_POWER_CONSUMPTION   = 500
ORAN_COOLING_POWER_CONSUMPTION      = 2000
    
# CORE CAPEX VALUES
CORE_BUY_COST           = 50000
CORE_COOLING_BUY_COST   = 5000

# CORE OPEX VALUES
CORE_POWER_CONSUMPTION          = 500
CORE_COOLING_POWER_CONSUMPTION  = 500


# POWER LINES CAPEX
POWER_LINE_LENGTH_KM 		= 10000
FRONTHAUL_MAX_LENGTH 		= 15
BASE_STATION_COVER_RADIUS 	= 5